version: '3'

services:
  app:
    image: node:21
    container_name: app
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start-dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
