version: '3'

services:
  app:
    image: node:21
    container_name: app
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: npm run start-dev
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb12345
    networks:
      - app-network

networks:
  app-network:
    driver: bridge